<h1><marquee><mark>AL Fahim Fuyad</mark></marquee></h1>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures
# A vector is one dimensional array of numbers. 
# A matrix is a two dimensional array of numbers.

**2. How to import `NumPy` library?** 

In [58]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [59]:
list_1 = [1,2,3,4,5]


In [60]:
# To avoid overwriting the output, please code here 
array_1 = np.array(list_1)
print(array_1)


[1 2 3 4 5]


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [61]:
# To avoid overwriting the output, please code here 
array_2 = np.arange(0, 5)
print(array_2)

[0 1 2 3 4]


**5. Generate an `array of "5" zeros` **

In [62]:
# To avoid overwriting the output, please code here 
array_2 = np.zeros((1,5))
print(array_2)

[[0. 0. 0. 0. 0.]]


**6. Generate the following `matrix`.**

In [63]:
# To avoid overwriting the output, please code here 
array_3 = np.zeros((3,4))
print(array_3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [64]:
# To avoid overwriting the output, please code here 
array_4 = np.ones((1,5))
print(array_4)

[[1. 1. 1. 1. 1.]]


**8. Generate an array of "5" tens.**

In [65]:
# To avoid overwriting the output, please code here 
array_5 = np.full(5,10)
array_5

array([10, 10, 10, 10, 10])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [66]:
# To avoid overwriting the output, please code here 
array_6 = np.arange(50,100,2)
array_6

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [67]:
# To avoid overwriting the output, please code here 
array_7 = np.linspace(0,1,10)
array_7

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [68]:
# To avoid overwriting the output, please code here 
array_8 = np.arange(0,25)
array_8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
# To avoid overwriting the output, please code here 
array_9 = np.array([1,2,3,4,5,6,7,8,9])
result = array_9.reshape(3,3)
result


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
# To avoid overwriting the output, please code here 
array_10 = np.arange(12)

array_10.shape = (3, 4)
print(array_10)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**12. Please generate the following matrix.**

In [72]:
# To avoid overwriting the output, please code here 
array_11 = np.arange(0.1,2.6,0.1).reshape(5,5)
array_11

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [73]:
# To avoid overwriting the output, please code here 
array_12 = np.linspace(0,24,25).reshape(5,5)
print(array_12)


[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


**14. What is the main difference between `linspace()` and `arange()`?**

In [74]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.


# linspace() creates a fixed number of equally spaced values between a start and end point (including the end).
# arange() creates values using a fixed step size and usually excludes the stop value.



**15. How to generate a single random integer number using NumPy built-in function?**

In [75]:
# To avoid overwriting the output, please code here 
array_13 = np.random.randint(100)
print(array_13)

23


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [76]:
# To avoid overwriting the output, please code here 
array_14 = np.random.rand(35).reshape(7,5)
print(array_14)

[[0.33088678 0.74063123 0.50497073 0.92849819 0.28954617]
 [0.50843159 0.76628592 0.63286533 0.79913352 0.60620691]
 [0.86475747 0.26514062 0.29976243 0.89965822 0.78169393]
 [0.09765081 0.43588288 0.46424444 0.46284855 0.59534927]
 [0.70057316 0.33224943 0.14137618 0.5725942  0.42947347]
 [0.60238199 0.52953321 0.40089626 0.59618665 0.06439725]
 [0.79684044 0.04951548 0.72290083 0.71799138 0.58267196]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [77]:
# To avoid overwriting the output, please code here 
array_15 = np.identity(5)*5
print(array_15)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 